export const types = {};

export type BorrowSupplyItem = {
  cToken: string;
  exchangeRateCurrent: string;
  supplyRatePerBlock: string;
  borrowRatePerBlock: string;
  reserveFactorMantissa: string;
  totalBorrows: string;
  totalReserves: string;
  totalSupply: string;
  totalCash: string;
  isListed: boolean;
  collateralFactorMantissa: string;
  underlyingAssetAddress: string;
  cTokenDecimals: string;
  underlyingDecimals: string;
  token: string;
  symbol: string;
  name: string;
  cName: string;
  exchangeRateStored: string;
  liquidity: number;
  isEnteredTheMarket: boolean;
  supplyAllowed: boolean;
  borrowAllowed: boolean;
  underlyingPrice: string;
  tokenBalance: string;
  tokenAllowance: string;
  borrowBalance: string;
  supplyBalance: string;
  balanceOf: string;
  earnedUsd: number;
  earnedUnderlying: number;
  balance: string;
  supply: string;
  borrow: string;
  supplyApy: number;
  borrowApy: number;
  tokenUsdValue: number;
  fiatSupply: number;
  fiatBorrow: number;
  supplyDistributionApy: number;
  borrowDistributionApy: number;
};
